### ISSUE TITLE
Login exception in latest 1.3.4998

### ISSUE THREAD

**Issue by tmandys** [cachewolf/cachewolf#1]
Cachewolf,exe cannot login to account so any cache update is impossible (Win7)

```
[gcLogin]
[gcLogin] Exception
ewe.io.IOException: URL: https://www.geocaching.com/account/login?RESET=Y
```

**Comment by arbor95** [comment]
See https://geoclub.de/forum/viewtopic.php?f=40&t=78734&start=40 for a temporary solution.

In short: put cookie gspkauth from browser to pref.xml and adjust validation date.

**Comment by tmandys** [comment]
Cookie expiration time prolongation workaround helped (<GCLogins expires="xxx" ....>) . Thanks

**Comment by arbor95** [comment]
You will need a new gspkauth after Expiration.

**Comment by ColleIsarco** [comment]
Has been solved in April. Therefore closed
